vich_uploader:
    db_driver: orm

    mappings:
        personage_speech_images:
            uri_prefix: /%app.path.personage_speech_images%
            upload_destination: '%kernel.project_dir%/public/%app.path.personage_speech_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer